[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-run --list-chips`
runner = "probe-run --chip ATSAMD21G18"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
